# Generated by Django 2.2.16 on 2022-03-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.CharField(default='Какое-то произведение', max_length=200, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='title_genre', to='reviews.Genres'),
            preserve_default=False,
        ),
    ]
