# Generated by Django 2.2.16 on 2022-03-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Genres'),
        ),
        migrations.DeleteModel(
            name='GenreTitles',
        ),
    ]
