# Generated by Django 2.2.16 on 2022-03-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220317_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='titles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.Titles'),
        ),
    ]
