# Generated by Django 2.2.16 on 2022-03-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220319_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titles',
            new_name='title',
        ),
    ]
