# Generated by Django 2.2.16 on 2022-03-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220319_1507'),
        ('reviews', '0008_auto_20220319_1717'),
    ]

    operations = [
    ]
