# Generated by Django 2.2.16 on 2022-03-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_20220319_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='titles',
        ),
    ]
