# Generated by Django 2.2.16 on 2022-03-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220320_1030'),
        ('reviews', '0016_auto_20220320_1330'),
    ]

    operations = [
    ]
