# Generated by Django 2.2.16 on 2022-03-21 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_merge_20220320_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Максимальное значение 10'), django.core.validators.MinValueValidator(1, 'Минимальное значение 1')]),
        ),
    ]
