# Generated by Django 2.2.16 on 2022-03-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_auto_20220321_1857'),
        ('reviews', '0018_auto_20220321_1601'),
    ]

    operations = [
    ]
